# Nom du workflow (visible dans l'onglet Actions sur GitHub)
name : Deploy Vite app to GitHub Pages

# Quand exécuter ce workflow
on:
  push:
    branches:
      - master  # lance le workflow automatiquement à chaque push sur master
  workflow_dispatch:  # permet aussi de le lancer manuellement depuis GitHub


# Définition des jobs à exécuter
jobs:
  build-and-deploy:   # Nom du job (on peut le changer)
    runs-on: ubuntu-latest   # la machine virtuelle utilisée
    steps:  # lise des étapes que GitHub va exécuter une par une

      # Télécharger le code depuis GitHub
      - name: Récupérer le code du dépot
        uses: actions/checkout@v4   # action officielle GitHub pour récupérer le code

      # Installer Node.js sur la machine
      - name: Installer Node.js
        uses: actions/setup-node@v4 #action officielle pour anstaller Node
        with:
          node-version: '18'

      # Installer toutes les dépendances du projet
      - name: Installer les dépendances 
        run: npm install  

      # Construire le projet Vite
      - name: Construire le projet Vite
        run: npm run build  # génère le dossier 'dist/' pour la production

      # Déployer le site sur GitHub Pages
      - name: Déployer sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4   # action externe pour déploiement
        with:
          branch: gh-pages  # branche où le site sera publié
          folder: dist    # dossier généré par Vite contenant le sie
